# Generated by Django 3.1.5 on 2021-01-07 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uid')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('address', models.CharField(max_length=300, verbose_name='adderss')),
                ('contact', models.CharField(max_length=13)),
                ('start_business_hours', models.DateTimeField()),
                ('end_business_hours', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospital List',
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uid')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('development_country', models.CharField(max_length=30, verbose_name='development_country')),
                ('development_company', models.CharField(max_length=30, verbose_name='development_company')),
                ('release_date', models.DateField(verbose_name='release_date')),
                ('kind', models.CharField(max_length=30, verbose_name='kind')),
                ('clinical_trial_stage', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccine List',
                'db_table': 'vaccine',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='uid')),
                ('reservation_time', models.DateTimeField(verbose_name='reservation_time')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reservations', to='inoculation.hospital', verbose_name='hospital')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservation List',
                'db_table': 'reservation',
            },
        ),
    ]
