# Generated by Django 3.1.5 on 2021-01-07 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inoculation', '0001_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reservations', to='inoculation.vaccine', verbose_name='vaccine'),
        ),
    ]
