# Generated by Django 3.1.5 on 2021-01-29 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoculation', '0002_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='place_url',
            field=models.URLField(default='', max_length=500, verbose_name='place_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='road_address',
            field=models.CharField(default='', max_length=300, verbose_name='road_address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=300, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact',
            field=models.CharField(max_length=13, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='end_business_hours',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_business_hours'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='start_business_hours',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_business_hours'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='clinical_trial_stage',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='clinical_trial_stage'),
        ),
    ]
