# Generated by Django 3.1.5 on 2021-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inoculation', '0003_add_road_addres_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hospital',
            unique_together={('latitude', 'longitude')},
        ),
    ]
