# Generated by Django 3.1.5 on 2021-05-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoculation', '0004_set_user_field_to_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='detail_name_code',
            field=models.CharField(default=1, max_length=50, verbose_name='detail_name_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccine',
            name='inoculation_count',
            field=models.CharField(default=1, max_length=30, verbose_name='inoculation_count'),
            preserve_default=False,
        ),
    ]
