# Generated by Django 3.1.5 on 2021-05-02 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoculation', '0005_add_some_field_info_vaccine_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='clinical_trial_stage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='clinical_trial_stage'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='release_date'),
        ),
    ]
